apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: homer
data:
  config.yml: |
    title: "DevOps Dashboard"
    subtitle: "All your hosted services & apps at a glance"
    logo: "assets/logo.png"
    header: true
    footer: '<p>Created with <span class="has-text-danger">❤️</span> using <a href="https://bulma.io/">Bulma</a>, <a href="https://vuejs.org/">Vue.js</a> & <a href="https://fontawesome.com/">Font Awesome</a></p>'
    columns: "3"
    connectivityCheck: true
    defaults:
      layout: columns
      colorTheme: auto
    theme: default
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#424242"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link: "#3273dc"
        link-hover: "#363636"
        background-image: "/assets/your/light/bg.png"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link: "#3273dc"
        link-hover: "#ffdd57"
        background-image: "/assets/your/dark/bg.png"

    message:
      style: "is-warning"
      title: "Reminder"
      icon: "fa fa-exclamation-triangle"
      content: "Regularly monitor HAProxy, databases, and Kubernetes cluster health."

    links:
      - name: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/bastienwirtz/homer"
        target: "_blank"
      - name: "Documentation"
        icon: "fas fa-book"
        url: "https://github.com/bastienwirtz/homer"

    services:
      - name: "Blogs"
        icon: "fas fa-globe"
        items:
          - name: "Personal Blog"
            icon: "fas fa-pencil-alt"
            url: "https://blog.r2b001.site"
            tag: "Blog"
            target: "_blank"
          - name: "Terminal Website"
            icon: "fas fa-flag-checkered"
            url: "https://terminal.app.r2b001.site"
            tag: "Terminal"
            target: "_blank"

      - name: "Applications"
        icon: "fas fa-th-large"
        items:
          - name: "Odoo ERP"
            icon: "fas fa-cogs"
            url: "https://odoo.app.r2b001.site"
            tag: "ERP"
            target: "_blank"
          - name: "CTFd Platform"
            icon: "fas fa-flag-checkered"
            url: "https://ctfd.app.r2b001.site"
            tag: "CTF"
            target: "_blank"

      - name: "Services"
        icon: "fas fa-server"
        items:
          - name: "Rancher K8s"
            icon: "fas fa-cubes"
            url: "https://rancher.service.r2b001.site"
            tag: "Kubernetes"
            target: "_blank"
          - name: "OAuth Service"
            icon: "fas fa-user-shield"
            url: "https://oauth.service.r2b001.site"
            tag: "Authentication"
            target: "_blank"

      - name: "APIs"
        icon: "fas fa-plug"
        items:
          - name: "n8n Automation"
            icon: "fas fa-project-diagram"
            url: "https://n8n.api.r2b001.site"
            tag: "Automation"
            target: "_blank"

      - name: "Databases"
        icon: "fas fa-database"
        items:
          - name: "PGAdmin"
            icon: "fas fa-database"
            url: "https://pgadmin.service.r2b001.site/pgadmin4"
            tag: "Database Admin"
            target: "_blank"
          - name: "Supabase"
            icon: "fas fa-database"
            url: "https://supabase.service.r2b001.site"
            tag: "Backend"
            target: "_blank"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-assets
  namespace: homer
data:
  favicon.ico: |
    (BASE64 OR RAW CONTENT)
  logo.png: |
    (BASE64 OR RAW CONTENT)
  grafana.png: |
    (BASE64 OR RAW CONTENT)
  k8s.png: |
    (BASE64 OR RAW CONTENT)
  custom.css: |
    body { background-color: #f0f0f0; }
